### ISSUE TITLE
can't reach archive page from navigation bar

### ISSUE THREAD

**Issue by JackLiar** [TheMicronaut/micronaut-theme#2]
The navigation bar url is https://domain/archive1/, and the actual reachable archive page url is https://domain/archive1.

You can see your github.io page, this problem occurs there too.

[unreachable](http://themicronaut.github.io/blog/)

[reachable](http://themicronaut.github.io/blog)

But what is weird is that this problem doesn't happen while locally building the blog site.

**Comment by TheMicronaut** [comment]
@JackWzh  Thank you for your feedback! Much appreciated.

The problem was related to trailing slashes. I had defined new permalinks for the archive pages, but among others, I didn't put trailing slashes properly.  This is now fixed.

As you rightly mentioned, this behavior occurs only on github's system, never locally. Perhaps there is an inconsistency on how permalinks are defined in the two systems. I'll also investigate this in the future.
